"""Init

Revision ID: 507af5495209
Revises: 
Create Date: 2023-01-18 18:47:17.378027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '507af5495209'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meteodatas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('odesa_air_temp', sa.Float(), nullable=True),
    sa.Column('odesa_wind_spd', sa.Float(), nullable=True),
    sa.Column('odesa__prc', sa.Float(), nullable=True),
    sa.Column('rivne_air_temp', sa.Float(), nullable=True),
    sa.Column('rivne_wind_spd', sa.Float(), nullable=True),
    sa.Column('rivne__prc', sa.Float(), nullable=True),
    sa.Column('baryshivka_air_temp', sa.Float(), nullable=True),
    sa.Column('baryshivka_wind_spd', sa.Float(), nullable=True),
    sa.Column('baryshivka_prc', sa.Float(), nullable=True),
    sa.Column('is_verify', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meteodatas')
    # ### end Alembic commands ###
