"""add created_by field

Revision ID: ad7c9a170a51
Revises: 507af5495209
Create Date: 2023-01-19 09:36:18.411221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad7c9a170a51'
down_revision = '507af5495209'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meteodatas', sa.Column('created_by', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meteodatas', 'created_by')
    # ### end Alembic commands ###
